### ISSUE TITLE
wa raises an exception on certain commands

### ISSUE THREAD

**Issue by co-robo** [coala/corobo#161]
Example: `corobo wa this is a sentence` raises an uncaught exception

difficulty/low importance/medium
traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/wolframalpha/__init__.py", line 88, in __getattr__
    val = self[name] if name in self else self[attr_name]
KeyError: '@pods'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/errbot/core.py", line 453, in _execute_and_send
    reply = method(mess, match) if match else method(mess, args)
  File "/opt/errbot/plugins/wolfram_alpha.py", line 24, in wa
    for pod in res.pods:
  File "/usr/local/lib/python3.6/site-packages/wolframalpha/__init__.py", line 90, in __getattr__
    raise AttributeError(name)
AttributeError: pods
```

**Comment by meetmangukiya** [comment]
https://github.com/jaraco/wolframalpha/issues/13
