### ISSUE TITLE
Disable LabHub when GitHub/GitLab token and org name isn't enabled

### ISSUE THREAD

**Issue by co-robo** [coala/corobo#253]
Opened by @yukiisbored at [gitter//yukiisbored](https://gitter.im//yukiisbored?at=598af6eb76a757f8088ab137)

**Comment by jayvdb** [comment]
During startup without a GitHub token in the environment (readme says it is optional) we see

```
22:05:43 ERROR    errbot.plugins.LabHub     Cannot create github object, please check GH_TOKEN
22:05:43 DEBUG    urllib3.connectionpool    Starting new HTTPS connection (1): api.github.com
...
20:20:56 DEBUG    urllib3.connectionpool    https://api.github.com:443 "GET /user/repos HTTP/1.1" 401 121
20:20:56 ERROR    errbot.plugins.LabHub     Something went wrong in fetching github repos.
Traceback (most recent call last):
  File "corobo/plugins/labhub.py", line 72, in __init__
    self.IGH.write_repositories)}
  File "../IGitt/GitHub/GitHub.py", line 67, in write_repositories
    repo_list = get(self._token, '/user/repos')
  File "../IGitt/GitHub/__init__.py", line 61, in get
    url, query_params=params, headers=headers)
  File "../IGitt/Interfaces/__init__.py", line 49, in wrap_func
    raise RuntimeError(response, code)
RuntimeError: ({'message': 'Requires authentication', 'documentation_url': 'https://developer.github.com/v3/repos/#list-your-repositories'}, 401)
```
