### ISSUE TITLE
Initialise GitHub repositories from a static file

### ISSUE THREAD

**Issue by jayvdb** [coala/corobo#357]
During startup without a GitHub token in the environment (readme says it is optional) we see

```
20:20:56 DEBUG    urllib3.connectionpool    https://api.github.com:443 "GET /user/repos HTTP/1.1" 401 121
20:20:56 ERROR    errbot.plugins.LabHub     Something went wrong in fetching github repos.
Traceback (most recent call last):
  File "corobo/plugins/labhub.py", line 72, in __init__
    self.IGH.write_repositories)}
  File "../IGitt/GitHub/GitHub.py", line 67, in write_repositories
    repo_list = get(self._token, '/user/repos')
  File "../IGitt/GitHub/__init__.py", line 61, in get
    url, query_params=params, headers=headers)
  File "../IGitt/Interfaces/__init__.py", line 49, in wrap_func
    raise RuntimeError(response, code)
RuntimeError: ({'message': 'Requires authentication', 'documentation_url': 'https://developer.github.com/v3/repos/#list-your-repositories'}, 401)
```

In the even this occurs, the bot should recognise this situation, and fallback to loading a pre-prepared static list stored in the repo, which will be good enough for most development needs.

**Comment by jayvdb** [comment]
This is almost a dup of https://github.com/coala/corobo/issues/253 .
I'll remove the token part , so it is only about type of token, as it needs to be an org admin token.
