### ISSUE TITLE
filters plugin uses msg.frm.room which does not exist for DMs on Zulip

### ISSUE THREAD

**Issue by jayvdb** [coala/corobo#407]
7dcc1e07 introduces filters.  On Zulip, in direct messages, this causes

```
Traceback (most recent call last):
  File "/.../errbot/errbot/core.py", line 345, in _process_command_filters
    msg, cmd, args = cmd_filter(msg, cmd, args, dry_run)
  File "/.../corobo/utils/filters.py", line 21, in filters
    if cmd in commands and msg.frm.room.uri == room:
AttributeError: 'ZulipPerson' object has no attribute 'room'
```

**Comment by jayvdb** [comment]
fyi. I need to recheck this.  There is a small chance that this was related to development only.
