### ISSUE TITLE
Docker image doesn't start

### ISSUE THREAD

**Issue by yukiisbored** [coala/corobo#629]
Due to a recent change with errbot, I believe it caused the Gitter backend to break and crash.

```
2018-10-18 13:04:41,521 INFO     errbot.bootstrap          Found Storage plugin: Shelf.
2018-10-18 13:04:41,530 INFO     errbot.bootstrap          Found Backend plugin: Gitter
2018-10-18 13:04:41,530 DEBUG    errbot.storage            Opening storage 'repomgr'
2018-10-18 13:04:41,531 DEBUG    errbot.storage.shelf      Open shelf storage /opt/errbot/data/repomgr.db
2018-10-18 13:04:41,543 ERROR    errbot.bootstrap          Unable to load or configure the backend.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/errbot/bootstrap.py", line 142, in setup_bot
    bot = backendpm.load_plugin()
  File "/usr/local/lib/python3.7/site-packages/errbot/backend_plugin_manager.py", line 43, in load_plugin
    plugin_classes = self.plugin_info.load_plugin_classes(self._base_module, self._base_class)
  File "/usr/local/lib/python3.7/site-packages/errbot/plugin_info.py", line 89, in load_plugin_classes
    spec.loader.exec_module(modu1e)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/errbot/err-backend-gitter/gitter.py", line 1, in <module>
    from errbot.errBot import ErrBot
ModuleNotFoundError: No module named 'errbot.errBot'
```

**Comment by jayvdb** [comment]
CI runs all tests.  That isnt possible if there is a problem like this.

It must be related to a specific version being different, but @abhishalya has been reporting a similar problem and they couldnt see what version was different.  However they were then reporting that all tests were passing locally, so they must have found a solution...

**Comment by abhishalya** [comment]
There was no solution other than manually changing the import statement to `from errbot.core import ErrBot`. @yukiisbored can you do the above change and try to deploy the bot again, I'm facing one more issue after that.
