### ISSUE TITLE
Travis CI build fails

### ISSUE THREAD

**Issue by codehobbyist06** [coala/corobo#667]
### Overview Description
The travis CI build for corobo is failing.
# Steps to Reproduce

1. Go to https://travis-ci.com
2. Run travis CI build for the coala/corobo repository

# Actual Results
Following are the errors occuring:
1.
```
tests/git_stats_test.py:4: in <module>
    from IGitt.GitHub.GitHubMergeRequest import GitHubMergeRequest
/usr/local/lib/python3.9/site-packages/IGitt/GitHub/__init__.py:13: in <module>
    from IGitt.Interfaces import Token, get, post
/usr/local/lib/python3.9/site-packages/IGitt/Interfaces/__init__.py:157: in <module>
    def get_response(method: Callable,
/usr/local/lib/python3.9/site-packages/backoff/_decorator.py:153: in decorate
    if asyncio.Task.current_task() is not None:
    AttributeError: type object '_asyncio.Task' has no attribute 'current_task'
```
2.
```
$ python -m pytest
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/manager.py", line 253, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2460, in load
    self.require(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2483, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pytest 3.6.4 (/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages), Requirement.parse('pytest>=4.6'))
```
3.
```
$ python -m pytest
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --doctest-ignore-import-error
```
4.
```
self = <tests.wolfram_alpha_test.WolframAlphaTest testMethod=test_wa>
    @my_vcr.use_cassette('tests/cassettes/wa.yaml')
    def test_wa(self):
        self.push_message('!wa 2^6')
        self.assertIn('64', self.pop_message())
        with self.assertLogs() as cm:
            self.assertCommand('!wa this is a sentence',
                               'Dunno')
        self.assertIn('INFO:errbot.plugins.WolframAlpha:KeyError triggered on '
>                     'retrieving pods.', cm.output)
       AssertionError: 'INFO:errbot.plugins.WolframAlpha:KeyError triggered on retrieving pods.' not found in
['INFO:errbot.plugins.ACLs:Matching ACL {} against username gbin@localhost for command WolframAlpha:wa.',
'INFO:errbot.plugins.ACLs:Check if wa is admin only command.', 'INFO:errbot.core:Processing command "wa" with
parameters "this is a sentence" from gbin@localhost', 'ERROR:errbot.core:callback_message on deprecate_bot_prefixes
crashed.\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.6/site-packages/errbot/core.py", line 111, in
_dispatch_to_plugins\n    getattr(plugin, method)(*args, **kwargs)\n  File "plugins/deprecate_bot_prefixes.py", line 15, in
callback_message\n    for deprecated_prefix in self.bot_config.BOT_DEPRECATED_PREFIXES:\nAttributeError:
\'ShallowConfig\' object has no attribute \'BOT_DEPRECATED_PREFIXES\'', 'INFO:vcr.stubs:Playing response for <Request
(GET) https://api.wolframalpha.com/v2/query?input=this+is+a+sentence&appid=None> from cassette',
'INFO:errbot.backends.test:\n\n\nMESSAGE:\nDunno :(\n\n\n']
tests/wolfram_alpha_test.py:22: AssertionError
```

# Expected Results
No errors. All tests should pass with 100% test coverage. All commands should exit with 0.

# Reproducibility
Every time

**Comment by codehobbyist06** [comment]
I have submitted a PR referencing this issue with the first three errors resolved. I am working on the fourth one.
